services:
  pgdatabase:
    container_name: pgdatabase
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "D:/Learn_UET/Learn Data Engineer/DE_Zoomcamp_2023/ny_taxi_postgre_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  ingestdata_v001:
    container_name: ingestdata_v001
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - user=root
        - password=root
        - host=pgdatabase
        - port=5432
        - db=ny_taxi
        - yellow_taxi_table=yellow_taxi_trips
        - green_taxi_table=green_taxi_trips
        - zones_data_table=zones
    stdin_open: true

